stages:
  - build
  - deploy

image-build:
  stage: build
  when: manual
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - |
      export CI_REGISTRY=$HARBOR_HOST
      export CI_REGISTRY_USER=$HARBOR_USERNAME
      export CI_REGISTRY_PASSWORD=$HARBOR_PASSWORD

      set -x
      TAG=$(cat composer.json | grep version | grep -Eo "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+")
      echo "Using TAG: $TAG"
      /kaniko/executor \
        --cache=true \
        --context "${CI_PROJECT_DIR}" \
        --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
        --destination "${HARBOR_HOST}/${HARBOR_PROJECT}/${IMAGE_NAME}:${TAG}"

deploy-dev:
  stage: deploy
  when: manual
  image:
    name: registry.neuropublic.gr:4443/neurocode-os/gitops
  script: |
    TAG=$(cat composer.json | grep version | grep -Eo "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+")

    init_kubeconfig.sh https://np-k8hps.neuropublic.gr:6443/ $DEV_NAMESPACE
    /gitlab/apply_deployment.sh \
      -n $IMAGE_NAME \
      -t $TAG \
      -s https://git.neuropublic.gr \
      -p 253 \
      -f $DEV_NAMESPACE/$KUBE_APP_LABEL/deployment.yaml
